apiVersion: v1
kind: Service
metadata:
  name: mainapp
  namespace: default
spec:
  selector:
    app: mainapp
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
      - name: mainapp
        image: k.xxxx.com:5000/py-web6.8:0
        ports:
        - containerPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-mainapp
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: vpn.testweb.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: mainapp
          servicePort: 80