# Deploy to aliyun

trigger:
- main
- dev
resources:
- repo: self


variables:
  BRANCH_NAME: $[upper(replace(variables['Build.SourceBranch'], 'refs/heads/', ''))]
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'eb779d0e-ca11-41b8-bff4-63517a93f17c'
  imageRepository: 'xtpython'
  containerRegistry: 'xtmagento.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'xtmagento80ab-auth'


  # Agent VM image name???
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      inputs:
        filePath: '/root/builddocker'
        


